import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const countFromLocalStorage =
  typeof window !== "undefined" ? Number(localStorage.getItem("count")) : 0;

const Home = () => {
  const [count, setCount] = useState(countFromLocalStorage);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>
          Count:
          {localStorage.getItem("count")}
        </h3>
        <button
          onClick={() => {
            window.localStorage.setItem("count", Number(count + 1));
            setCount(count + 1);
          }}
        >
          Click to increase count
        </button>
      </main>
    </>
  );
};
export default dynamic(() => Promise.resolve(Home), {
  ssr: false,
});
